#!/usr/bin/env bash
set -euo pipefail

tmp_dir="$(mktemp -d)"
tmp_override="${tmp_dir}/distill-override.yml"
tmp_site="${tmp_dir}/site"
distill_fixture="_posts/2021-05-22-distill.md"

cleanup() {
  rm -f "${distill_fixture}"
  rm -rf "${tmp_dir}"
}
trap cleanup EXIT

if [[ -e "${distill_fixture}" ]]; then
  echo "refusing to overwrite an existing Distill fixture" >&2
  exit 1
fi

cat >"${distill_fixture}" <<'MARKDOWN'
---
layout: distill
title: Distill integration fixture
date: 2021-05-22
giscus_comments: true
related_posts: false
sitemap: false
mermaid:
  enabled: true
tikzjax: true
authors:
  - name: Integration Test
    affiliations:
      name: al-folio
---

Temporary fixture generated by `test/integration_distill.sh`.
MARKDOWN

cat >"${tmp_override}" <<'YAML'
giscus:
  repo: alshedivat/al-folio
  repo_id: R_kgDOExample
  category: Comments
  category_id: DIC_kwDOExample
YAML

bundle exec jekyll build --config "_config.yml,${tmp_override}" -d "${tmp_site}" >/dev/null

distill_page="${tmp_site}/blog/2021/distill/index.html"

if [ ! -f "${distill_page}" ]; then
  echo "distill page was not generated at ${distill_page}" >&2
  exit 1
fi

assert_contains() {
  local pattern="$1"
  local description="$2"
  if ! grep -q "${pattern}" "${distill_page}"; then
    echo "${description} missing from ${distill_page}" >&2
    exit 1
  fi
}

assert_contains 'd-front-matter' 'Distill front matter element'
assert_contains '/assets/js/distillpub/template.v2.js' 'Distill template runtime'
assert_contains '/assets/js/distillpub/transforms.v2.js' 'Distill transforms runtime'
assert_contains '/assets/js/distillpub/overrides.js' 'Distill overrides runtime'
assert_contains '/assets/al_charts/js/mermaid-setup.js' 'Mermaid setup runtime'
assert_contains 'https://cdn.jsdelivr.net/npm/@planktimerr/tikzjax@1.0.8/dist/fonts.css' 'TikZJax stylesheet'
assert_contains 'https://cdn.jsdelivr.net/npm/@planktimerr/tikzjax@1.0.8/dist/tikzjax.js' 'TikZJax runtime'
assert_contains 'id="giscus_thread"' 'Giscus thread container'
transforms_runtime="${tmp_site}/assets/js/distillpub/transforms.v2.js"
distill_runtime="$(PATH="$HOME/.rbenv/shims:$PATH" bundle exec ruby -e 'spec = Gem.loaded_specs["al_folio_distill"]; puts(spec ? File.join(spec.full_gem_path, "assets/js/distillpub/transforms.v2.js") : "")')"
if [ -f "${distill_runtime}" ]; then
  # Prefer the packaged gem runtime for deterministic parity checks.
  transforms_runtime="${distill_runtime}"
elif [ ! -f "${transforms_runtime}" ]; then
  echo "distill transforms runtime missing at ${transforms_runtime} (and not found in installed al_folio_distill gem)" >&2
  exit 1
fi

expected_transforms_hash="5d85590f5652b910ab2411019749c83ef5a5a3fbb9b739adc92b4557b6bf3d39"
actual_transforms_hash="$(ruby -rdigest -e 'print Digest::SHA256.file(ARGV[0]).hexdigest' "${transforms_runtime}")"
if [ "${actual_transforms_hash}" != "${expected_transforms_hash}" ]; then
  echo "unexpected distill transforms runtime hash: ${actual_transforms_hash}" >&2
  exit 1
fi

echo "distill integration checks passed"
